const COUNTRY_FLAGS: Record<string, string> = {
  україна: '🇺🇦',
  украина: '🇺🇦',
  ukraine: '🇺🇦',
  польща: '🇵🇱',
  poland: '🇵🇱',
  німеччина: '🇩🇪',
  germany: '🇩🇪',
  франція: '🇫🇷',
  france: '🇫🇷',
  італія: '🇮🇹',
  italy: '🇮🇹',
  іспанія: '🇪🇸',
  spain: '🇪🇸',
  туреччина: '🇹🇷',
  turkey: '🇹🇷',
  греція: '🇬🇷',
  greece: '🇬🇷',
  чехія: '🇨🇿',
  czechia: '🇨🇿',
  австрія: '🇦🇹',
  austria: '🇦🇹',
  угорщина: '🇭🇺',
  hungary: '🇭🇺',
  великобританія: '🇬🇧',
  'united kingdom': '🇬🇧',
  uk: '🇬🇧',
  сша: '🇺🇸',
  usa: '🇺🇸',
  'united states': '🇺🇸',
  японія: '🇯🇵',
  japan: '🇯🇵',
  тайланд: '🇹🇭',
  thailand: '🇹🇭',
  єгипет: '🇪🇬',
  egypt: '🇪🇬',
  норвегія: '🇳🇴',
  norway: '🇳🇴',
  швейцарія: '🇨🇭',
  switzerland: '🇨🇭',
  хорватія: '🇭🇷',
  croatia: '🇭🇷',
  грузія: '🇬🇪',
  georgia: '🇬🇪',
  канада: '🇨🇦',
  canada: '🇨🇦',
  португалія: '🇵🇹',
  portugal: '🇵🇹',
  нідерланди: '🇳🇱',
  netherlands: '🇳🇱'
}

export function countryFlag(country: string): string {
  const key = country.trim().toLowerCase()
  return COUNTRY_FLAGS[key] ?? '🌍'
}
